[project]
name = "python-docker-example"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Builkdite Developers", email = "dev@buildkite.com" }
]
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
