steps:
- label: run pytest
  agents:
    queue: kubernetes
  plugins:
  - kubernetes:
      podSpec:
        containers:
        - image: python:latest
          command: [.buildkite/steps/test.sh]
          envFrom:
            - secretRef:
                name: buildkite-analytics
  - test-collector:
      files: "junit-*.xml"
      format: "junit"
